# more info see: https://golangci-lint.run/usage/configuration/
linters:
  enable:
    - govet
    - misspell
  disable:
    - unused
  disable-all: false
  presets:
  fast: false

# all available settings of specific linters
linters-settings: