language: go

env:
  global:
    - GO111MODULE=on


before_script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.38.0

script:
  - make lint